=== yo2752/cole/IntegracionSigaWS/WebContent/WEB-INF/services/IntegracionSigaWS/com/integracionsigaWS/esquemasXSD/PlantillaBajas.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xs:element name="FORMATO_OEGAM2_BAJA">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CABECERA" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="BAJA" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="FechaCreacion" type="xs:string" use="optional"/>
			<xs:attribute name="Plataforma" type="xs:string" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="CABECERA">
		<xs:complexType>
			<xs:all>
				<xs:element ref="DATOS_GESTORIA"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="DATOS_GESTORIA">
		<xs:complexType>
			<xs:all>
				<xs:element ref="NIF"/>
				<xs:element ref="NOMBRE"/>
				<xs:element ref="PROFESIONAL"/>
				<xs:element ref="PROVINCIA"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="BAJA">
		<xs:complexType>
			<xs:all>
				<xs:element ref="NUMERO_EXPEDIENTE" minOccurs="0"/>
				<xs:element ref="REFERENCIA_PROPIA" minOccurs="0"/>
				<xs:element ref="PROFESIONAL" minOccurs="0"/>
				<xs:element ref="FECHA_CREACION" minOccurs="0"/>
				<xs:element ref="OBSERVACIONES" minOccurs="0"/>
				<xs:element ref="MOTIVO_BAJA" minOccurs="0"/>
				<xs:element ref="PERMISO_CIRCULACION" minOccurs="0"/>
				<xs:element ref="TARJETA_INSPECCION_TECNICA" minOccurs="0"/>
				<xs:element ref="BAJA_IMVTM" minOccurs="0"/>
				<xs:element ref="JUSTIFICANTE_DENUNCIA" minOccurs="0"/>
				<xs:element ref="DOCUMENTO_PROPIEDAD" minOccurs="0"/>
				<xs:element ref="JUSTIFICANTE_IMVTM" minOccurs="0"/>
				<xs:element ref="DATOS_VEHICULO" minOccurs="0"/>
				<xs:element ref="DATOS_TITULAR" minOccurs="0"/>
				<xs:element ref="DATOS_REPRESENTANTE" minOccurs="0"/>				
				<xs:element ref="DATOS_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="DATOS_PAGO_PRESENTACION" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="DATOS_VEHICULO">
		<xs:complexType>
			<xs:all>
				<xs:element ref="MATRICULA" minOccurs="0"/>
				<xs:element ref="FECHA_MATRICULACION" minOccurs="0"/>
				<xs:element ref="PROVINCIA_VEHICULO" minOccurs="0"/>
				<xs:element ref="MUNICIPIO_VEHICULO" minOccurs="0"/>
				<xs:element ref="PUEBLO_VEHICULO" minOccurs="0"/>
				<xs:element ref="CODIGO_POSTAL_VEHICULO" minOccurs="0"/>
				<xs:element ref="TIPO_VIA_VEHICULO" minOccurs="0"/>
				<xs:element ref="CALLE_DIRECCION_VEHICULO" minOccurs="0"/>
				<xs:element ref="NUMERO_DIRECCION_VEHICULO" minOccurs="0"/>
				<xs:element ref="LETRA_DIRECCION_VEHICULO" minOccurs="0"/>
				<xs:element ref="ESCALERA_DIRECCION_VEHICULO" minOccurs="0"/>
				<xs:element ref="PISO_DIRECCION_VEHICULO" minOccurs="0"/>
				<xs:element ref="PUERTA_DIRECCION_VEHICULO" minOccurs="0"/>
				<xs:element ref="BLOQUE_DIRECCION_VEHICULO" minOccurs="0"/>
				<xs:element ref="KM_DIRECCION_VEHICULO" minOccurs="0"/>
				<xs:element ref="HM_DIRECCION_VEHICULO" minOccurs="0"/>
				<xs:element ref="FECHA_ITV" minOccurs="0"/>
				<xs:element ref="ES_SINIESTRO" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	
	
	
	<xs:element name="DATOS_TITULAR">
		<xs:complexType>
			<xs:all>
				<xs:element ref="DNI_TITULAR" minOccurs="0"/>
				<xs:element ref="SEXO_TITULAR" minOccurs="0"/>
				<xs:element ref="APELLIDO1_RAZON_SOCIAL_TITULAR" minOccurs="0"/>
				<xs:element ref="APELLIDO2_TITULAR" minOccurs="0"/>
				<xs:element ref="NOMBRE_TITULAR" minOccurs="0"/>
				<xs:element ref="PROVINCIA_TITULAR" minOccurs="0"/>
				<xs:element ref="MUNICIPIO_TITULAR" minOccurs="0"/>
				<xs:element ref="PUEBLO_TITULAR" minOccurs="0"/>
				<xs:element ref="CODIGO_POSTAL_TITULAR" minOccurs="0"/>
				<xs:element ref="TIPO_VIA_TITULAR" minOccurs="0"/>
				<xs:element ref="CALLE_DIRECCION_TITULAR" minOccurs="0"/>
				<xs:element ref="NUMERO_DIRECCION_TITULAR" minOccurs="0"/>
				<xs:element ref="LETRA_DIRECCION_TITULAR" minOccurs="0"/>
				<xs:element ref="ESCALERA_DIRECCION_TITULAR" minOccurs="0"/>
				<xs:element ref="PISO_DIRECCION_TITULAR" minOccurs="0"/>
				<xs:element ref="PUERTA_DIRECCION_TITULAR" minOccurs="0"/>
				<xs:element ref="BLOQUE_DIRECCION_TITULAR" minOccurs="0"/>
				<xs:element ref="KM_DIRECCION_TITULAR" minOccurs="0"/>
				<xs:element ref="HM_DIRECCION_TITULAR" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	
	
	<xs:element name="DATOS_REPRESENTANTE">
		<xs:complexType>
			<xs:all>
				<xs:element ref="DNI_REPRESENTANTE" minOccurs="0"/>
				<xs:element ref="SEXO_REPRESENTANTE" minOccurs="0"/>
				<xs:element ref="APELLIDO1_RAZON_SOCIAL_REPRESENTANTE" minOccurs="0"/>
				<xs:element ref="APELLIDO2_REPRESENTANTE" minOccurs="0"/>
				<xs:element ref="NOMBRE_REPRESENTANTE" minOccurs="0"/>				
				<xs:element ref="CONCEPTO_REPRESENTANTE" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	
	
	
	<xs:element name="DATOS_ADQUIRIENTE">
		<xs:complexType>
			<xs:all>
				<xs:element ref="DNI_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="SEXO_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="APELLIDO1_RAZON_SOCIAL_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="APELLIDO2_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="NOMBRE_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="FECHA_NACIMIENTO_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="PROVINCIA_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="MUNICIPIO_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="PUEBLO_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="CODIGO_POSTAL_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="TIPO_VIA_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="CALLE_DIRECCION_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="NUMERO_DIRECCION_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="LETRA_DIRECCION_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="ESCALERA_DIRECCION_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="PISO_DIRECCION_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="PUERTA_DIRECCION_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="BLOQUE_DIRECCION_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="KM_DIRECCION_ADQUIRIENTE" minOccurs="0"/>
				<xs:element ref="HM_DIRECCION_ADQUIRIENTE" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	
	<xs:element name="DATOS_PAGO_PRESENTACION">
		<xs:complexType>
			<xs:all>
				<xs:element ref="CODIGO_TASA" minOccurs="0"/>
				<xs:element ref="JEFATURA_PROVINCIAL" minOccurs="0"/>
				<xs:element ref="FECHA_PRESENTACION" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	

	<xs:element name="NIF" type="tipoNIF"/>
	<xs:element name="NOMBRE" type="alfa50"/>
	<xs:element name="PROFESIONAL" type="alfa4"/>
	<xs:element name="PROVINCIA" type="alfa2"/>
	
	<xs:element name="NUMERO_EXPEDIENTE" type="alfa50"/>
	<xs:element name="REFERENCIA_PROPIA" type="alfa50"/>
	<xs:element name="FECHA_CREACION" type="tipoFecha"/>
	<xs:element name="OBSERVACIONES" type="alfa255"/>
	<xs:element name="MOTIVO_BAJA" type="motivoBaja"/>
	<xs:element name="PERMISO_CIRCULACION" type="tipoSiNo"/>
	<xs:element name="TARJETA_INSPECCION_TECNICA" type="tipoSiNo"/>
	<xs:element name="BAJA_IMVTM" type="tipoSiNo"/>
	<xs:element name="JUSTIFICANTE_DENUNCIA" type="tipoSiNo"/>
	<xs:element name="DOCUMENTO_PROPIEDAD" type="tipoSiNo"/>
	<xs:element name="JUSTIFICANTE_IMVTM" type="tipoSiNo"/>
	
	<xs:element name="MATRICULA" type="alfa9"/>
	<xs:element name="FECHA_MATRICULACION" type="tipoFecha"/>
	<xs:element name="PROVINCIA_VEHICULO" type="alfa2"/>
	<xs:element name="MUNICIPIO_VEHICULO" type="alfa3"/>
	<xs:element name="PUEBLO_VEHICULO" type="alfa50"/>
	<xs:element name="CODIGO_POSTAL_VEHICULO" type="alfa5"/>
	<xs:element name="TIPO_VIA_VEHICULO" type="tipoVia"/>
	<xs:element name="CALLE_DIRECCION_VEHICULO" type="alfa50"/>
	<xs:element name="NUMERO_DIRECCION_VEHICULO" type="alfa4"/>
	<xs:element name="LETRA_DIRECCION_VEHICULO" type="alfa2"/>
	<xs:element name="ESCALERA_DIRECCION_VEHICULO" type="alfa2"/>
	<xs:element name="PISO_DIRECCION_VEHICULO" type="alfa2"/>
	<xs:element name="PUERTA_DIRECCION_VEHICULO" type="alfa2"/>
	<xs:element name="BLOQUE_DIRECCION_VEHICULO" type="alfa2"/>
	<xs:element name="KM_DIRECCION_VEHICULO" type="alfa3"/>
	<xs:element name="HM_DIRECCION_VEHICULO" type="alfa3"/>
	<xs:element name="FECHA_ITV" type="tipoFecha"/>
	<xs:element name="ES_SINIESTRO" type="tipoSiNo"/>
	
	
	<xs:element name="DNI_TITULAR" type="tipoNIF"/>
	<xs:element name="SEXO_TITULAR" type="tipoSexo"/>
	<xs:element name="APELLIDO1_RAZON_SOCIAL_TITULAR" type="alfa50"/>
	<xs:element name="APELLIDO2_TITULAR" type="alfa50"/>
	<xs:element name="NOMBRE_TITULAR" type="alfa50"/>
	<xs:element name="PROVINCIA_TITULAR" type="alfa2"/>
	<xs:element name="MUNICIPIO_TITULAR" type="alfa3"/>
	<xs:element name="PUEBLO_TITULAR" type="alfa50"/>
	<xs:element name="CODIGO_POSTAL_TITULAR" type="alfa5"/>
	<xs:element name="TIPO_VIA_TITULAR" type="tipoVia"/>
	<xs:element name="CALLE_DIRECCION_TITULAR" type="alfa50"/>
	<xs:element name="NUMERO_DIRECCION_TITULAR" type="alfa4"/>
	<xs:element name="LETRA_DIRECCION_TITULAR" type="alfa2"/>
	<xs:element name="ESCALERA_DIRECCION_TITULAR" type="alfa2"/>
	<xs:element name="PISO_DIRECCION_TITULAR" type="alfa2"/>
	<xs:element name="PUERTA_DIRECCION_TITULAR" type="alfa2"/>
	<xs:element name="BLOQUE_DIRECCION_TITULAR" type="alfa2"/>
	<xs:element name="KM_DIRECCION_TITULAR" type="alfa3"/>
	<xs:element name="HM_DIRECCION_TITULAR" type="alfa3"/>
	
	<xs:element name="DNI_REPRESENTANTE" type="tipoNIF"/>
	<xs:element name="SEXO_REPRESENTANTE" type="tipoSexo"/>
	<xs:element name="APELLIDO1_RAZON_SOCIAL_REPRESENTANTE" type="alfa50"/>
	<xs:element name="APELLIDO2_REPRESENTANTE" type="alfa50"/>
	<xs:element name="NOMBRE_REPRESENTANTE" type="alfa50"/>
	<xs:element name="CONCEPTO_REPRESENTANTE" type="conceptoRepresentante"/>
	
	<xs:element name="DNI_ADQUIRIENTE" type="tipoNIF"/>
	<xs:element name="SEXO_ADQUIRIENTE" type="tipoSexo"/>
	<xs:element name="APELLIDO1_RAZON_SOCIAL_ADQUIRIENTE" type="alfa50"/>
	<xs:element name="APELLIDO2_ADQUIRIENTE" type="alfa50"/>
	<xs:element name="NOMBRE_ADQUIRIENTE" type="alfa50"/>
	<xs:element name="FECHA_NACIMIENTO_ADQUIRIENTE" type="tipoFecha"/>
	<xs:element name="PROVINCIA_ADQUIRIENTE" type="alfa2"/>
	<xs:element name="MUNICIPIO_ADQUIRIENTE" type="alfa3"/>
	<xs:element name="PUEBLO_ADQUIRIENTE" type="alfa50"/>
	<xs:element name="CODIGO_POSTAL_ADQUIRIENTE" type="alfa5"/>
	<xs:element name="TIPO_VIA_ADQUIRIENTE" type="tipoVia"/>
	<xs:element name="CALLE_DIRECCION_ADQUIRIENTE" type="alfa50"/>
	<xs:element name="NUMERO_DIRECCION_ADQUIRIENTE" type="alfa4"/>
	<xs:element name="LETRA_DIRECCION_ADQUIRIENTE" type="alfa2"/>
	<xs:element name="ESCALERA_DIRECCION_ADQUIRIENTE" type="alfa2"/>
	<xs:element name="PISO_DIRECCION_ADQUIRIENTE" type="alfa2"/>
	<xs:element name="PUERTA_DIRECCION_ADQUIRIENTE" type="alfa2"/>
	<xs:element name="BLOQUE_DIRECCION_ADQUIRIENTE" type="alfa2"/>
	<xs:element name="KM_DIRECCION_ADQUIRIENTE" type="alfa3"/>
	<xs:element name="HM_DIRECCION_ADQUIRIENTE" type="alfa3"/>
	
	<xs:element name="CODIGO_TASA" type="alfa12"/>
	<xs:element name="JEFATURA_PROVINCIAL" type="alfa2"/>
	<xs:element name="FECHA_PRESENTACION" type="tipoFecha"/>
	
	
	<xs:simpleType name="alfa2">
		<xs:restriction base="xs:string">
			<xs:maxLength value="2"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="alfa3">
		<xs:restriction base="xs:string">
			<xs:maxLength value="3"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="alfa4">
		<xs:restriction base="xs:string">
			<xs:maxLength value="4"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="alfa5">
		<xs:restriction base="xs:string">
			<xs:maxLength value="5"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="alfa9">
		<xs:restriction base="xs:string">
			<xs:maxLength value="9"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="alfa12">
		<xs:restriction base="xs:string">
			<xs:maxLength value="12"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="alfa50">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tipoNIF">
		<xs:restriction base="xs:string">
			<xs:pattern value="[kKlL0-9]{1}[0-9]{7}[a-zA-Z]{1}|[mMxXyYzZ]{1}[0-9]{7}[a-zA-Z]{1}|[a-hA-HjJuUvV]{1}[0-9]{8}|[p-sP-SnNwW]{1}[0-9]{7}[a-jA-J]{1}|.{0}"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="tipoFecha">
		<xs:restriction base="xs:string">
			<xs:pattern value="(0[1-9]|[1-2][0-9]|30|31)/(0[1-9]|10|11|12)/([1-9][0-9][0-9][0-9])|.{0}"/>
		</xs:restriction>
	</xs:simpleType>
	
	
	
	<xs:simpleType name="tipoSiNo">
		<xs:restriction base="xs:string">
			<xs:maxLength value="2"/>
			<xs:enumeration value=""/>
			<xs:enumeration value="SI"/>
			<xs:enumeration value="NO"/>
			<xs:enumeration value="Si"/>
			<xs:enumeration value="No"/>
			<xs:enumeration value="si"/>
			<xs:enumeration value="no"/>
		</xs:restriction>
	</xs:simpleType>
	
	
	
	<xs:simpleType name="motivoBaja">
		<xs:restriction base="xs:string">
			<xs:enumeration value=""/>
			<xs:maxLength value="2"/>
			<xs:enumeration value="-1"/>
			<xs:enumeration value="1"/>
			<xs:enumeration value="2"/>
			<xs:enumeration value="3"/>
			<xs:enumeration value="4"/>
			<xs:enumeration value="5"/>
			<xs:enumeration value="6"/>
			<xs:enumeration value="7"/>
			<xs:enumeration value="8"/>
		</xs:restriction>
	</xs:simpleType>
	
	
	<xs:simpleType name="conceptoRepresentante">
		<xs:restriction base="xs:string">
			<xs:enumeration value=""/>
			<xs:maxLength value="24"/>
			<xs:enumeration value="TUTELA O PATRIA POTESTAD"/>
			<xs:enumeration value="ADMINISTRADOR"/>
			<xs:enumeration value="APODERADO"/>
			<xs:enumeration value="REPRESENTANTE"/>
		</xs:restriction>
	</xs:simpleType>
	
	
	
	<xs:simpleType name="alfa255">
		<xs:restriction base="xs:string">
			<xs:maxLength value="255"/>
		</xs:restriction>
	</xs:simpleType>
	
	
	
	<xs:simpleType name="tipoSexo">
		<xs:restriction base="xs:string">
			<xs:enumeration value=""/>
			<xs:enumeration value="V"/>
			<xs:enumeration value="H"/>
			<xs:enumeration value="X"/>
		</xs:restriction>
	</xs:simpleType>
	
	
	<xs:simpleType name="tipoVia">
		<xs:restriction base="xs:string">
			<xs:enumeration value=""/>
			<xs:enumeration value="-1"/>
			<xs:enumeration value="ACCES"/>
			<xs:enumeration value="ALAM"/>
			<xs:enumeration value="ALDEA"/>
			<xs:enumeration value="ALTO"/>
			<xs:enumeration value="APTOS"/>
			<xs:enumeration value="ARRAL"/>
			<xs:enumeration value="ARRY"/>
			<xs:enumeration value="ATAJO"/>
			<xs:enumeration value="AUTO"/>
			<xs:enumeration value="AVIA"/>
			<xs:enumeration value="AVDA"/>
			<xs:enumeration value="BJADA"/>
			<xs:enumeration value="BRANC"/>
			<xs:enumeration value="BARDA"/>
			<xs:enumeration value="BARRO"/>
			<xs:enumeration value="."/>
			<xs:enumeration value="BLQUE"/>
			<xs:enumeration value="BULEV"/>
			<xs:enumeration value="CALLE"/>
			<xs:enumeration value="CLLJA"/>
			<xs:enumeration value="CLLON"/>
			<xs:enumeration value="CJLA"/>
			<xs:enumeration value="CZADA"/>
			<xs:enumeration value="CAMI"/>
			<xs:enumeration value="CAMIN"/>
			<xs:enumeration value="CMNO"/>
			<xs:enumeration value="CAMPA"/>
			<xs:enumeration value="CANAL"/>
			<xs:enumeration value="CÑADA"/>
			<xs:enumeration value="CRA"/>
			<xs:enumeration value="CTRA"/>
			<xs:enumeration value="CTRIN"/>
			<xs:enumeration value="CRRIL"/>
			<xs:enumeration value="CSRIO"/>
			<xs:enumeration value="CERRO"/>
			<xs:enumeration value="CINT"/>
			<xs:enumeration value="C.H."/>
			<xs:enumeration value="C.N."/>
			<xs:enumeration value="C.V."/>
			<xs:enumeration value="COL"/>
			<xs:enumeration value="COMPJ"/>
			<xs:enumeration value="CJTO"/>
			<xs:enumeration value="CRRAL"/>
			<xs:enumeration value="CRRLO"/>
			<xs:enumeration value="CRRDE"/>
			<xs:enumeration value="CRRDO"/>
			<xs:enumeration value="CRTJO"/>
			<xs:enumeration value="COSTA"/>
			<xs:enumeration value="CSTAN"/>
			<xs:enumeration value="CUSTA"/>
			<xs:enumeration value="ENTD"/>
			<xs:enumeration value="ESCA"/>
			<xs:enumeration value="ESCAL"/>
			<xs:enumeration value="EXPLA"/>
			<xs:enumeration value="EXTRM"/>
			<xs:enumeration value="EXTRR"/>
			<xs:enumeration value="FINCA"/>
			<xs:enumeration value="GALE"/>
			<xs:enumeration value="GTA"/>
			<xs:enumeration value="G.V."/>
			<xs:enumeration value="GRUPO"/>
			<xs:enumeration value="GRUP"/>
			<xs:enumeration value="JDIN"/>
			<xs:enumeration value="LDERA"/>
			<xs:enumeration value="LUGAR"/>
			<xs:enumeration value="MALEC"/>
			<xs:enumeration value="MIRAD"/>
			<xs:enumeration value="MONTE"/>
			<xs:enumeration value="MUELL"/>
			<xs:enumeration value="PAGO"/>
			<xs:enumeration value="PRAJE"/>
			<xs:enumeration value="PARKE"/>
			<xs:enumeration value="PQUE"/>
			<xs:enumeration value="PARC"/>
			<xs:enumeration value="PARTI"/>
			<xs:enumeration value="PTDA"/>
			<xs:enumeration value="PZO"/>
			<xs:enumeration value="PSAJE"/>
			<xs:enumeration value="PASEO"/>
			<xs:enumeration value="PSLLO"/>
			<xs:enumeration value="PISTA"/>
			<xs:enumeration value="PLCET"/>
			<xs:enumeration value="PLAZA"/>
			<xs:enumeration value="PZTA"/>
			<xs:enumeration value="PLZLA"/>
			<xs:enumeration value="PBDO"/>
			<xs:enumeration value="POLIG"/>
			<xs:enumeration value="PTLLO"/>
			<xs:enumeration value="PRAZA"/>
			<xs:enumeration value="PROL"/>
			<xs:enumeration value="PNTE"/>
			<xs:enumeration value="PTO"/>
			<xs:enumeration value="RAMAL"/>
			<xs:enumeration value="RBLA"/>
			<xs:enumeration value="RBRA"/>
			<xs:enumeration value="RCON"/>
			<xs:enumeration value="RCDA"/>
			<xs:enumeration value="RONDA"/>
			<xs:enumeration value="RTDA"/>
			<xs:enumeration value="SECT"/>
			<xs:enumeration value="SENDA"/>
			<xs:enumeration value="SEND"/>
			<xs:enumeration value="SBIDA"/>
			<xs:enumeration value="TRAS"/>
			<xs:enumeration value="TRVA"/>
			<xs:enumeration value="TRAV"/>
			<xs:enumeration value="URB"/>
			<xs:enumeration value="VALLE"/>
			<xs:enumeration value="VEGA"/>
			<xs:enumeration value="VREDA"/>
			<xs:enumeration value="VIA"/>
			<xs:enumeration value="VCTO"/>
			<xs:enumeration value="VIAL"/>
			<xs:enumeration value="ZONA"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== yo2752/cole/IntegracionSigaWS/WebContent/WEB-INF/services/IntegracionSigaWS/com/integracionsigaWS/esquemasXSD/PlantillaBajas.xml
<?xml version="1.0" encoding="UTF-8"?>
<FORMATO_OEGAM2_BAJA FechaCreacion="" Plataforma="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PlantillaBajas.xsd">
  <CABECERA>
    <DATOS_GESTORIA>
      <NIF>48505575R</NIF>
      <NOMBRE>JULIO</NOMBRE>
      <PROFESIONAL>PROF</PROFESIONAL>
      <PROVINCIA>MU</PROVINCIA>
    </DATOS_GESTORIA>
  </CABECERA>
  <BAJA>
    <NUMERO_EXPEDIENTE>NUMERO_EXPEDIENTE</NUMERO_EXPEDIENTE>
    <REFERENCIA_PROPIA>REFERENCIA_PROPIA</REFERENCIA_PROPIA>
    <PROFESIONAL>PRO</PROFESIONAL>
    <FECHA_CREACION>12/05/1984</FECHA_CREACION>
    <OBSERVACIONES>OBSERVACIONES</OBSERVACIONES>
    <MOTIVO_BAJA></MOTIVO_BAJA>
    <PERMISO_CIRCULACION></PERMISO_CIRCULACION>
    <TARJETA_INSPECCION_TECNICA></TARJETA_INSPECCION_TECNICA>
    <BAJA_IMVTM></BAJA_IMVTM>
    <JUSTIFICANTE_DENUNCIA></JUSTIFICANTE_DENUNCIA>
    <DOCUMENTO_PROPIEDAD></DOCUMENTO_PROPIEDAD>
    <JUSTIFICANTE_IMVTM></JUSTIFICANTE_IMVTM>
    <DATOS_VEHICULO>
      <MATRICULA>MATRICULA</MATRICULA>
      <FECHA_MATRICULACION>12/05/1984</FECHA_MATRICULACION>
      <PROVINCIA_VEHICULO>MU</PROVINCIA_VEHICULO>
      <MUNICIPIO_VEHICULO>MU</MUNICIPIO_VEHICULO>
      <PUEBLO_VEHICULO>PUEBLO_VEHICULO</PUEBLO_VEHICULO>
      <CODIGO_POSTAL_VEHICULO>30002</CODIGO_POSTAL_VEHICULO>
      <TIPO_VIA_VEHICULO></TIPO_VIA_VEHICULO>
      <CALLE_DIRECCION_VEHICULO>CALLE_DIRECCION_VEHICULO</CALLE_DIRECCION_VEHICULO>
      <NUMERO_DIRECCION_VEHICULO>AA</NUMERO_DIRECCION_VEHICULO>
      <LETRA_DIRECCION_VEHICULO>SS</LETRA_DIRECCION_VEHICULO>
      <ESCALERA_DIRECCION_VEHICULO>2</ESCALERA_DIRECCION_VEHICULO>
      <PISO_DIRECCION_VEHICULO>3</PISO_DIRECCION_VEHICULO>
      <PUERTA_DIRECCION_VEHICULO>G</PUERTA_DIRECCION_VEHICULO>
      <BLOQUE_DIRECCION_VEHICULO>A</BLOQUE_DIRECCION_VEHICULO>
      <KM_DIRECCION_VEHICULO>100</KM_DIRECCION_VEHICULO>
      <HM_DIRECCION_VEHICULO>200</HM_DIRECCION_VEHICULO>
    </DATOS_VEHICULO>
    <DATOS_TITULAR>
      <DNI_TITULAR>48505575R</DNI_TITULAR>
      <SEXO_TITULAR></SEXO_TITULAR>
      <APELLIDO1_RAZON_SOCIAL_TITULAR>APELLIDO1_RAZON_SOCIAL_TITULAR</APELLIDO1_RAZON_SOCIAL_TITULAR>
      <APELLIDO2_TITULAR>APELLIDO2_TITULAR</APELLIDO2_TITULAR>
      <NOMBRE_TITULAR>NOMBRE_TITULAR</NOMBRE_TITULAR>
      <PROVINCIA_TITULAR>MU</PROVINCIA_TITULAR>
      <MUNICIPIO_TITULAR>MU</MUNICIPIO_TITULAR>
      <PUEBLO_TITULAR>PUEBLO_TITULAR</PUEBLO_TITULAR>
      <CODIGO_POSTAL_TITULAR>30002</CODIGO_POSTAL_TITULAR>
      <TIPO_VIA_TITULAR></TIPO_VIA_TITULAR>
      <CALLE_DIRECCION_TITULAR>CALLE_DIRECCION_TITULAR</CALLE_DIRECCION_TITULAR>
      <NUMERO_DIRECCION_TITULAR>6</NUMERO_DIRECCION_TITULAR>
      <LETRA_DIRECCION_TITULAR>A</LETRA_DIRECCION_TITULAR>
      <ESCALERA_DIRECCION_TITULAR>2</ESCALERA_DIRECCION_TITULAR>
      <PISO_DIRECCION_TITULAR>3</PISO_DIRECCION_TITULAR>
      <PUERTA_DIRECCION_TITULAR>G</PUERTA_DIRECCION_TITULAR>
      <BLOQUE_DIRECCION_TITULAR>A</BLOQUE_DIRECCION_TITULAR>
      <KM_DIRECCION_TITULAR>300</KM_DIRECCION_TITULAR>
      <HM_DIRECCION_TITULAR>500</HM_DIRECCION_TITULAR>
    </DATOS_TITULAR>
    <DATOS_REPRESENTANTE>
      <DNI_REPRESENTANTE>48505575R</DNI_REPRESENTANTE>
      <SEXO_REPRESENTANTE></SEXO_REPRESENTANTE>
      <APELLIDO1_RAZON_SOCIAL_REPRESENTANTE>APELLIDO1_RAZON_SOCIAL_REPRESENTANTE</APELLIDO1_RAZON_SOCIAL_REPRESENTANTE>
      <APELLIDO2_REPRESENTANTE>APELLIDO2_REPRESENTANTE</APELLIDO2_REPRESENTANTE>
      <NOMBRE_REPRESENTANTE>NOMBRE_REPRESENTANTE</NOMBRE_REPRESENTANTE>
      <CONCEPTO_REPRESENTANTE></CONCEPTO_REPRESENTANTE>
    </DATOS_REPRESENTANTE>
    <DATOS_ADQUIRIENTE>
      <DNI_ADQUIRIENTE>48505575R</DNI_ADQUIRIENTE>
      <SEXO_ADQUIRIENTE></SEXO_ADQUIRIENTE>
      <APELLIDO1_RAZON_SOCIAL_ADQUIRIENTE>APELLIDO1_RAZON_SOCIAL_ADQUIRIENTE</APELLIDO1_RAZON_SOCIAL_ADQUIRIENTE>
      <APELLIDO2_ADQUIRIENTE>APELLIDO2_ADQUIRIENTE</APELLIDO2_ADQUIRIENTE>
      <NOMBRE_ADQUIRIENTE>NOMBRE_ADQUIRIENTE</NOMBRE_ADQUIRIENTE>
      <FECHA_NACIMIENTO_ADQUIRIENTE>12/05/1984</FECHA_NACIMIENTO_ADQUIRIENTE>
      <PROVINCIA_ADQUIRIENTE>MU</PROVINCIA_ADQUIRIENTE>
      <MUNICIPIO_ADQUIRIENTE>MU</MUNICIPIO_ADQUIRIENTE>
      <PUEBLO_ADQUIRIENTE>PUEBLO_ADQUIRIENTE</PUEBLO_ADQUIRIENTE>
      <CODIGO_POSTAL_ADQUIRIENTE>30002</CODIGO_POSTAL_ADQUIRIENTE>
      <TIPO_VIA_ADQUIRIENTE></TIPO_VIA_ADQUIRIENTE>
      <CALLE_DIRECCION_ADQUIRIENTE>CALLE_DIRECCION_ADQUIRIENTE</CALLE_DIRECCION_ADQUIRIENTE>
      <NUMERO_DIRECCION_ADQUIRIENTE>8</NUMERO_DIRECCION_ADQUIRIENTE>
      <LETRA_DIRECCION_ADQUIRIENTE>W</LETRA_DIRECCION_ADQUIRIENTE>
      <ESCALERA_DIRECCION_ADQUIRIENTE>A</ESCALERA_DIRECCION_ADQUIRIENTE>
      <PISO_DIRECCION_ADQUIRIENTE>5</PISO_DIRECCION_ADQUIRIENTE>
      <PUERTA_DIRECCION_ADQUIRIENTE>3</PUERTA_DIRECCION_ADQUIRIENTE>
      <BLOQUE_DIRECCION_ADQUIRIENTE>a</BLOQUE_DIRECCION_ADQUIRIENTE>
      <KM_DIRECCION_ADQUIRIENTE>800</KM_DIRECCION_ADQUIRIENTE>
      <HM_DIRECCION_ADQUIRIENTE>900</HM_DIRECCION_ADQUIRIENTE>
    </DATOS_ADQUIRIENTE>
    <DATOS_PAGO_PRESENTACION>
      <CODIGO_TASA>CODIGO_TASA</CODIGO_TASA>
      <JEFATURA_PROVINCIAL>MU</JEFATURA_PROVINCIAL>
      <FECHA_PRESENTACION>12/05/1984</FECHA_PRESENTACION>
    </DATOS_PAGO_PRESENTACION>
  </BAJA>
</FORMATO_OEGAM2_BAJA>
